import { chromium } from "playwright";
const url = process.argv[2];
const out = process.argv[3];
const b = await chromium.launch({ args: ["--no-sandbox"] });
const p = await b.newPage({ viewport: { width: 1280, height: 760 } });
const errs = [];
p.on("pageerror", e => errs.push(e.message));
await p.goto(url, { waitUntil: "domcontentloaded", timeout: 120000 });
await p.waitForTimeout(3000);
const secure = await p.evaluate(() => ({ isSecure: window.isSecureContext, hasUUID: typeof crypto?.randomUUID === "function", hasSubtle: !!(crypto && crypto.subtle) }));
console.log("ctx:", JSON.stringify(secure));
await p.waitForSelector(".raze-chart-root canvas", { timeout: 30000 }).then(()=>console.log("chart canvas: PRESENT")).catch(()=>console.log("chart canvas: ABSENT"));
await p.waitForTimeout(7000);
await p.screenshot({ path: out });
console.log("shot:", out);
if (errs.length) console.log("pageerrors:", errs.slice(0,6).join(" | ")); else console.log("no pageerrors");
await b.close();
