// Flattens the TradingView-compatible declaration barrel into one file.
//
// src/types/charting_library.d.ts is a barrel that re-exports the domain
// modules under src/types/tv/. The package publishes that module tree under
// dist/types, and build.mjs also writes one self-contained copy to
// dist/charting_library.d.ts and dist/datafeed-api.d.ts so the file can be
// vendored next to a bundle (the TradingView Charting Library layout) without
// the module tree.
//
// Flattening is only sound when the modules follow a few rules, so they are
// enforced here instead of producing a subtly different file:
//   - the barrel contains only `export * from "./tv/<module>"` statements;
//   - a module declares with `export` on every top-level declaration;
//   - a module refers to its siblings only through
//     `import type { A, B } from "./<module>"` (no renames, no values), and
//     every imported sibling is itself re-exported by the barrel;
//   - no two modules declare the same name;
//   - every src/types/tv/*.d.ts module is re-exported by the barrel.

import { existsSync, readdirSync, readFileSync } from "node:fs";
import { dirname, relative, resolve, sep } from "node:path";
import ts from "typescript";

export const COMPATIBILITY_BARREL = "src/types/charting_library.d.ts";

const GENERATED_NOTE = [
  "// Generated by build.mjs from src/types/charting_library.d.ts and the",
  "// src/types/tv/*.d.ts modules it re-exports. Edit those sources instead.",
].join("\n");

const DECLARATION_KINDS = new Set([
  ts.SyntaxKind.InterfaceDeclaration,
  ts.SyntaxKind.TypeAliasDeclaration,
  ts.SyntaxKind.ClassDeclaration,
  ts.SyntaxKind.FunctionDeclaration,
  ts.SyntaxKind.VariableStatement,
  ts.SyntaxKind.EnumDeclaration,
  ts.SyntaxKind.ModuleDeclaration,
]);

class CompatibilityTypesError extends Error {
  constructor(file, node, message) {
    const location = node
      ? `${file}:${node.getSourceFile().getLineAndCharacterOfPosition(node.getStart()).line + 1}`
      : file;
    super(`[raze-charts] ${location}: ${message}`);
    this.name = "CompatibilityTypesError";
  }
}

/** LF line endings, no trailing blanks, at most one empty line in a row. */
const normalizeNewlines = (text) => text
  .replace(/\r\n?/g, "\n")
  .replace(/[ \t]+$/gm, "")
  .replace(/\n{3,}/g, "\n\n")
  .trim();

const parse = (path) => ts.createSourceFile(path, readFileSync(path, "utf8"), ts.ScriptTarget.Latest, true);

function declaredNames(statement) {
  if (ts.isVariableStatement(statement)) {
    return statement.declarationList.declarations.map((declaration) => declaration.name.getText());
  }
  return statement.name ? [statement.name.getText()] : [];
}

const hasModifier = (node, kind) => (ts.canHaveModifiers(node) ? ts.getModifiers(node) : undefined)
  ?.some((modifier) => modifier.kind === kind) ?? false;

/** `./x`, `./x.js` and `./x.d.ts` all name the sibling `x.d.ts`. */
const moduleFile = (directory, specifier) =>
  resolve(directory, `${specifier.replace(/\.(?:d\.ts|js)$/, "")}.d.ts`);

/**
 * Returns the flattened, self-contained declaration text for the barrel at
 * `options.barrel` (default: src/types/charting_library.d.ts under `root`).
 * Throws a CompatibilityTypesError naming the file, line and fix when a module
 * breaks one of the flattening rules above.
 */
export function bundleCompatibilityTypes(root, { barrel = COMPATIBILITY_BARREL } = {}) {
  const display = (path) => relative(root, path).split(sep).join("/");
  const barrelPath = resolve(root, barrel);
  const barrelFile = parse(barrelPath);
  const barrelText = barrelFile.getFullText();

  const modules = [];
  for (const statement of barrelFile.statements) {
    const specifier = ts.isExportDeclaration(statement)
      && !statement.exportClause
      && !statement.isTypeOnly
      && statement.moduleSpecifier
      && ts.isStringLiteral(statement.moduleSpecifier)
      ? statement.moduleSpecifier.text
      : undefined;
    if (!specifier || !/^\.\/tv\/[\w-]+(?:\.js|\.d\.ts)?$/.test(specifier)) {
      throw new CompatibilityTypesError(
        display(barrelPath),
        statement,
        "the barrel may only contain `export * from \"./tv/<module>\"` statements. "
          + "Declare the type in a src/types/tv/ module and re-export that module here.",
      );
    }
    const path = moduleFile(dirname(barrelPath), specifier);
    if (!existsSync(path)) {
      throw new CompatibilityTypesError(display(barrelPath), statement, `re-exported module ${display(path)} does not exist.`);
    }
    if (modules.some((module) => module.path === path)) {
      throw new CompatibilityTypesError(display(barrelPath), statement, `${display(path)} is re-exported twice.`);
    }
    modules.push({ path, leading: barrelText.slice(statement.getFullStart(), statement.getStart()) });
  }
  if (!modules.length) {
    throw new CompatibilityTypesError(display(barrelPath), undefined, "the barrel re-exports no src/types/tv modules.");
  }

  const barrelModules = new Set(modules.map((module) => module.path));
  const moduleDirectory = resolve(dirname(barrelPath), "tv");
  const orphans = readdirSync(moduleDirectory)
    .filter((entry) => entry.endsWith(".d.ts") && !barrelModules.has(resolve(moduleDirectory, entry)));
  if (orphans.length) {
    throw new CompatibilityTypesError(
      display(barrelPath),
      undefined,
      `${orphans.map((entry) => display(resolve(moduleDirectory, entry))).join(", ")} `
        + `${orphans.length === 1 ? "is" : "are"} not re-exported. Add \`export * from "./tv/<module>"\` `
        + "to the barrel so the declarations are published.",
    );
  }
  const owners = new Map();
  const sections = [];
  for (const module of modules) {
    const file = parse(module.path);
    const name = display(module.path);
    const text = file.getFullText();
    const removed = [];
    for (const statement of file.statements) {
      if (ts.isImportDeclaration(statement)) {
        const clause = statement.importClause;
        const specifier = ts.isStringLiteral(statement.moduleSpecifier) ? statement.moduleSpecifier.text : "";
        const namedOnly = clause && !clause.name && clause.namedBindings && ts.isNamedImports(clause.namedBindings);
        if (!clause?.isTypeOnly || !namedOnly || !/^\.\/[\w-]+(?:\.js|\.d\.ts)?$/.test(specifier)) {
          throw new CompatibilityTypesError(
            name,
            statement,
            "modules may only import sibling types as `import type { A, B } from \"./<module>\"`.",
          );
        }
        const renamed = clause.namedBindings.elements.find((element) => element.propertyName);
        if (renamed) {
          throw new CompatibilityTypesError(
            name,
            renamed,
            `rename "${renamed.getText()}" cannot survive flattening; import the declaration under its own name.`,
          );
        }
        const target = moduleFile(dirname(module.path), specifier);
        if (!barrelModules.has(target)) {
          throw new CompatibilityTypesError(
            name,
            statement,
            `${display(target)} is not re-exported by ${display(barrelPath)}, so its declarations would be `
              + "missing from the flattened file. Re-export it from the barrel.",
          );
        }
        removed.push([statement.getStart(), statement.getEnd()]);
        continue;
      }
      if (!DECLARATION_KINDS.has(statement.kind)) {
        throw new CompatibilityTypesError(
          name,
          statement,
          "modules may only contain type-only sibling imports and exported declarations "
            + "(re-exports belong in the barrel).",
        );
      }
      if (!hasModifier(statement, ts.SyntaxKind.ExportKeyword) || hasModifier(statement, ts.SyntaxKind.DefaultKeyword)) {
        throw new CompatibilityTypesError(
          name,
          statement,
          "every top-level declaration must be a named `export`; a module-private declaration would "
            + "become public in the flattened file.",
        );
      }
      for (const declared of declaredNames(statement)) {
        const owner = owners.get(declared);
        if (owner && owner !== name) {
          throw new CompatibilityTypesError(
            name,
            statement,
            `"${declared}" is also declared in ${owner}; flattening would merge the two declarations.`,
          );
        }
        owners.set(declared, name);
      }
    }
    let body = text;
    for (const [start, end] of removed.reverse()) body = body.slice(0, start) + body.slice(end);
    body = normalizeNewlines(body);
    const leading = normalizeNewlines(module.leading);
    sections.push(leading && sections.length ? `${leading}\n${body}` : body);
  }

  const header = normalizeNewlines(modules[0].leading);
  return `${header ? `${header}\n\n` : ""}${GENERATED_NOTE}\n\n${sections.join("\n\n")}\n`;
}
